--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BINZIP_MEMBER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BINZIP_MEMBER" 
   (	"IDX" NUMBER(10,0), 
	"ID" VARCHAR2(50 BYTE), 
	"PWD" VARCHAR2(50 BYTE), 
	"QUESTION" VARCHAR2(100 BYTE), 
	"ANSWER" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"BIRTHDATE" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"JOINDATE" DATE, 
	"GRADE" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.BINZIP_MEMBER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007116
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C007116" ON "SCOTT"."BINZIP_MEMBER" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007117
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C007117" ON "SCOTT"."BINZIP_MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BINZIP_MEMBER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BINZIP_MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_MEMBER" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."BINZIP_MEMBER" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."BINZIP_MEMBER" MODIFY ("GRADE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_MEMBER" MODIFY ("JOINDATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_MEMBER" MODIFY ("BIRTHDATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_MEMBER" MODIFY ("ANSWER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_MEMBER" MODIFY ("QUESTION" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_MEMBER" MODIFY ("PWD" NOT NULL ENABLE);
