--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BINZIP_HOST_BBS_IMGS
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BINZIP_HOST_BBS_IMGS" 
   (	"IDX" NUMBER(10,0), 
	"BINZIP_HOST_BBS_IDX" NUMBER(10,0), 
	"IMGPATH" VARCHAR2(3000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.BINZIP_HOST_BBS_IMGS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BINZIP_HOST_BBS_IMGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."BINZIP_HOST_BBS_IMGS_PK" ON "SCOTT"."BINZIP_HOST_BBS_IMGS" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BINZIP_HOST_BBS_IMGS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BINZIP_HOST_BBS_IMGS" ADD CONSTRAINT "BINZIP_HOST_BBS_IMGS_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."BINZIP_HOST_BBS_IMGS" MODIFY ("IMGPATH" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HOST_BBS_IMGS" MODIFY ("BINZIP_HOST_BBS_IDX" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HOST_BBS_IMGS" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BINZIP_HOST_BBS_IMGS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BINZIP_HOST_BBS_IMGS" ADD CONSTRAINT "BINZIP_HOST_BBS_IMGS_FK1" FOREIGN KEY ("IDX")
	  REFERENCES "SCOTT"."BINZIP_HOST_BBS" ("IDX") ON DELETE CASCADE DISABLE;
