--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BINZIP_HELP_BBS
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BINZIP_HELP_BBS" 
   (	"IDX" NUMBER(10,0), 
	"BINZIP_MEMBER_ID" VARCHAR2(50 BYTE), 
	"SUBJECT" VARCHAR2(200 BYTE), 
	"CONTENTS" VARCHAR2(3000 BYTE), 
	"READNUM" NUMBER(20,0), 
	"WRITEDATE" DATE, 
	"STATUS" NUMBER(2,0), 
	"REF" NUMBER(10,0), 
	"LEV" NUMBER(10,0), 
	"STEP" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.BINZIP_HELP_BBS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BINZIP_HELP_BBS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."BINZIP_HELP_BBS_PK" ON "SCOTT"."BINZIP_HELP_BBS" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BINZIP_HELP_BBS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BINZIP_HELP_BBS" ADD CONSTRAINT "BINZIP_HELP_BBS_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."BINZIP_HELP_BBS" MODIFY ("STEP" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HELP_BBS" MODIFY ("LEV" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HELP_BBS" MODIFY ("REF" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HELP_BBS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HELP_BBS" MODIFY ("WRITEDATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HELP_BBS" MODIFY ("READNUM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HELP_BBS" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HELP_BBS" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HELP_BBS" MODIFY ("BINZIP_MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HELP_BBS" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BINZIP_HELP_BBS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BINZIP_HELP_BBS" ADD CONSTRAINT "BINZIP_HELP_BBS_FK1" FOREIGN KEY ("BINZIP_MEMBER_ID")
	  REFERENCES "SCOTT"."BINZIP_MEMBER" ("ID") ON DELETE CASCADE DISABLE;
