--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BINZIP_RESERVE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BINZIP_RESERVE" 
   (	"BINZIP_MEMBER_ID" VARCHAR2(50 BYTE), 
	"BINZIP_HOST_BBS_IDX" NUMBER(10,0), 
	"RESERVE_STARTDATE" DATE, 
	"RESERVE_ENDDATE" DATE, 
	"PEOPLENUM" NUMBER(4,0), 
	"RESERVER_NAME" VARCHAR2(50 BYTE), 
	"RESERVER_PHONE" VARCHAR2(100 BYTE), 
	"PAYER" VARCHAR2(50 BYTE), 
	"RESERVER_BANK" VARCHAR2(30 BYTE), 
	"RESERVER_ACNUMBER" VARCHAR2(100 BYTE), 
	"COST" NUMBER(10,0), 
	"REQUEST" VARCHAR2(3000 BYTE), 
	"STATUS" NUMBER(2,0), 
	"TODAYDATE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.BINZIP_RESERVE
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table BINZIP_RESERVE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BINZIP_RESERVE" ADD CONSTRAINT "BINZIP_RESERVE_PK" PRIMARY KEY ("BINZIP_HOST_BBS_IDX") DISABLE;
  ALTER TABLE "SCOTT"."BINZIP_RESERVE" MODIFY ("TODAYDATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_RESERVE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_RESERVE" MODIFY ("COST" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_RESERVE" MODIFY ("RESERVER_ACNUMBER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_RESERVE" MODIFY ("RESERVER_BANK" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_RESERVE" MODIFY ("PAYER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_RESERVE" MODIFY ("RESERVER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_RESERVE" MODIFY ("RESERVER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_RESERVE" MODIFY ("PEOPLENUM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_RESERVE" MODIFY ("RESERVE_ENDDATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_RESERVE" MODIFY ("RESERVE_STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_RESERVE" MODIFY ("BINZIP_HOST_BBS_IDX" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_RESERVE" MODIFY ("BINZIP_MEMBER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BINZIP_RESERVE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BINZIP_RESERVE" ADD CONSTRAINT "BINZIP_RESERVE_FK1" FOREIGN KEY ("BINZIP_MEMBER_ID")
	  REFERENCES "SCOTT"."BINZIP_MEMBER" ("ID") ON DELETE CASCADE DISABLE;
