--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BINZIP_OPTION
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BINZIP_OPTION" 
   (	"IDX" NUMBER(10,0), 
	"CATEGORY" NUMBER(2,0), 
	"OP" VARCHAR2(20 BYTE), 
	"STATUS" NUMBER(2,0), 
	"BINZIP_HOST_BBS_IDX" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.BINZIP_OPTION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BINZIP_OPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."BINZIP_OPTION_PK" ON "SCOTT"."BINZIP_OPTION" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BINZIP_OPTION
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BINZIP_OPTION" ADD CONSTRAINT "BINZIP_OPTION_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."BINZIP_OPTION" MODIFY ("BINZIP_HOST_BBS_IDX" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_OPTION" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_OPTION" MODIFY ("OP" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_OPTION" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_OPTION" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BINZIP_OPTION
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BINZIP_OPTION" ADD CONSTRAINT "BINZIP_OPTION_FK1" FOREIGN KEY ("IDX")
	  REFERENCES "SCOTT"."BINZIP_HOST_BBS" ("IDX") ON DELETE CASCADE DISABLE;
