--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BINZIP_HOST
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BINZIP_HOST" 
   (	"IDX" NUMBER(10,0), 
	"BINZIP_MEMBER_ID" VARCHAR2(50 BYTE), 
	"BANK" VARCHAR2(30 BYTE), 
	"ACNUMBER" VARCHAR2(100 BYTE), 
	"STARTDATE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.BINZIP_HOST
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BINZIP_HOST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."BINZIP_HOST_PK" ON "SCOTT"."BINZIP_HOST" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BINZIP_HOST
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BINZIP_HOST" ADD CONSTRAINT "BINZIP_HOST_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."BINZIP_HOST" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HOST" MODIFY ("ACNUMBER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HOST" MODIFY ("BANK" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HOST" MODIFY ("BINZIP_MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_HOST" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BINZIP_HOST
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BINZIP_HOST" ADD CONSTRAINT "BINZIP_HOST_FK1" FOREIGN KEY ("BINZIP_MEMBER_ID")
	  REFERENCES "SCOTT"."BINZIP_MEMBER" ("ID") ON DELETE CASCADE DISABLE;
