--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BINZIP_BOOKMARK
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BINZIP_BOOKMARK" 
   (	"IDX" NUMBER(10,0), 
	"BINZIP_HOST_BBS_IDX" NUMBER(10,0), 
	"BINZIP_MEMBER_ID" VARCHAR2(50 BYTE), 
	"STATUS" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.BINZIP_BOOKMARK
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."TABLE1_PK" ON "SCOTT"."BINZIP_BOOKMARK" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BINZIP_BOOKMARK
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BINZIP_BOOKMARK" ADD CONSTRAINT "BINZIP_BOOKMARK_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."BINZIP_BOOKMARK" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_BOOKMARK" MODIFY ("BINZIP_MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_BOOKMARK" MODIFY ("BINZIP_HOST_BBS_IDX" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BINZIP_BOOKMARK" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BINZIP_BOOKMARK
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BINZIP_BOOKMARK" ADD CONSTRAINT "BINZIP_BOOKMARK_FK1" FOREIGN KEY ("IDX")
	  REFERENCES "SCOTT"."BINZIP_HOST_BBS" ("IDX") ON DELETE CASCADE DISABLE;
  ALTER TABLE "SCOTT"."BINZIP_BOOKMARK" ADD CONSTRAINT "BINZIP_BOOKMARK_FK2" FOREIGN KEY ("BINZIP_MEMBER_ID")
	  REFERENCES "SCOTT"."BINZIP_MEMBER" ("ID") ON DELETE CASCADE DISABLE;
